# Generated by Django 4.1.3 on 2022-11-16 21:44

from django.db import migrations

def migrate_author_to_contributors(apps, schema_editor):
    Blog = apps.get_model('blog', 'Blog')
    for blog in Blog.objects.all():
        if blog.author:
            blog.contributors.add(blog.author,
                                  through_defaults={'contribution': 'Auteur principal'})

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_author_blogcontributor_blog_contributors'),
    ]

    operations = [
        migrations.RunPython(migrate_author_to_contributors)
    ]
